trigger:
- devops-terraform

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      # Install Terraform
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      sudo apt-get update && sudo apt-get install terraform

    displayName: 'Install Terraform'

  - script: |
      # Initialize Terraform
      cd TerrafomCode
      terraform init

    displayName: 'Terraform Init'

  - script: |
      # Plan Terraform changes
      cd TerrafomCode
      terraform plan -out=tfplan

    displayName: 'Terraform Plan'

  - script: |
      # Apply Terraform changes
      cd TerrafomCode
      terraform apply -auto-approve tfplan

    displayName: 'Terraform Apply'


